
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE work_record;
TRUNCATE TABLE employee;
DELETE FROM user WHERE role = 'EMPLOYEE';

ALTER TABLE work_record AUTO_INCREMENT = 1;
ALTER TABLE employee AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;


-- TRUNCATE TABLE work_project;
-- ALTER TABLE work_project AUTO_INCREMENT = 1;
